"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .sdkerror import SDKError
from typing import Any, TYPE_CHECKING

from attio.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .delete_v2_comments_comment_id_op import (
        DeleteV2CommentsCommentIDNotFoundError,
        DeleteV2CommentsCommentIDNotFoundErrorData,
    )
    from .delete_v2_files_file_id_op import (
        DeleteV2FilesFileIDNotFoundError,
        DeleteV2FilesFileIDNotFoundErrorData,
    )
    from .delete_v2_lists_list_entries_entry_id_op import (
        DeleteV2ListsListEntriesEntryIDNotFoundError,
        DeleteV2ListsListEntriesEntryIDNotFoundErrorData,
    )
    from .delete_v2_meetings_meeting_id_call_recordings_call_recording_id_op import (
        DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundError,
        DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData,
    )
    from .delete_v2_notes_note_id_op import (
        DeleteV2NotesNoteIDNotFoundError,
        DeleteV2NotesNoteIDNotFoundErrorData,
    )
    from .delete_v2_objects_object_records_record_id_op import (
        DeleteV2ObjectsObjectRecordsRecordIDNotFoundError,
        DeleteV2ObjectsObjectRecordsRecordIDNotFoundErrorData,
    )
    from .delete_v2_tasks_task_id_op import (
        DeleteV2TasksTaskIDNotFoundError,
        DeleteV2TasksTaskIDNotFoundErrorData,
    )
    from .delete_v2_webhooks_webhook_id_op import (
        DeleteV2WebhooksWebhookIDNotFoundError,
        DeleteV2WebhooksWebhookIDNotFoundErrorData,
    )
    from .get_v2_comments_comment_id_op import (
        GetV2CommentsCommentIDNotFoundError,
        GetV2CommentsCommentIDNotFoundErrorData,
    )
    from .get_v2_files_file_id_op import (
        GetV2FilesFileIDNotFoundError,
        GetV2FilesFileIDNotFoundErrorData,
    )
    from .get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop import (
        GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundError,
        GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundErrorData,
    )
    from .get_v2_lists_list_entries_entry_id_op import (
        GetV2ListsListEntriesEntryIDNotFoundError,
        GetV2ListsListEntriesEntryIDNotFoundErrorData,
    )
    from .get_v2_lists_list_op import (
        GetV2ListsListNotFoundError,
        GetV2ListsListNotFoundErrorData,
    )
    from .get_v2_lists_list_viewsop import (
        GetV2ListsListViewsNotFoundError,
        GetV2ListsListViewsNotFoundErrorData,
    )
    from .get_v2_meetings_meeting_id_call_recordings_call_recording_id_op import (
        GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundError,
        GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData,
    )
    from .get_v2_meetings_meeting_id_op import (
        GetV2MeetingsMeetingIDNotFoundError,
        GetV2MeetingsMeetingIDNotFoundErrorData,
    )
    from .get_v2_notes_note_id_op import (
        GetV2NotesNoteIDNotFoundError,
        GetV2NotesNoteIDNotFoundErrorData,
    )
    from .get_v2_notesop import GetV2NotesNotFoundError, GetV2NotesNotFoundErrorData
    from .get_v2_objects_object_op import (
        GetV2ObjectsObjectNotFoundError,
        GetV2ObjectsObjectNotFoundErrorData,
    )
    from .get_v2_objects_object_records_record_id_attributes_attribute_valuesop import (
        GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundError,
        GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundErrorData,
        GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeError,
        GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeErrorData,
    )
    from .get_v2_objects_object_records_record_id_op import (
        GetV2ObjectsObjectRecordsRecordIDNotFoundError,
        GetV2ObjectsObjectRecordsRecordIDNotFoundErrorData,
    )
    from .get_v2_objects_object_viewsop import (
        GetV2ObjectsObjectViewsNotFoundError,
        GetV2ObjectsObjectViewsNotFoundErrorData,
    )
    from .get_v2_target_identifier_attributes_attribute_op import (
        GetV2TargetIdentifierAttributesAttributeNotFoundError,
        GetV2TargetIdentifierAttributesAttributeNotFoundErrorData,
    )
    from .get_v2_target_identifier_attributes_attribute_optionsop import (
        GetV2TargetIdentifierAttributesAttributeOptionsNotFoundError,
        GetV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData,
    )
    from .get_v2_target_identifier_attributes_attribute_statusesop import (
        GetV2TargetIdentifierAttributesAttributeStatusesNotFoundError,
        GetV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData,
    )
    from .get_v2_tasks_task_id_op import (
        GetV2TasksTaskIDNotFoundError,
        GetV2TasksTaskIDNotFoundErrorData,
    )
    from .get_v2_threads_thread_id_op import (
        GetV2ThreadsThreadIDNotFoundError,
        GetV2ThreadsThreadIDNotFoundErrorData,
    )
    from .get_v2_webhooks_webhook_id_op import (
        GetV2WebhooksWebhookIDNotFoundError,
        GetV2WebhooksWebhookIDNotFoundErrorData,
    )
    from .get_v2_workspace_members_workspace_member_id_op import (
        GetV2WorkspaceMembersWorkspaceMemberIDNotFoundError,
        GetV2WorkspaceMembersWorkspaceMemberIDNotFoundErrorData,
    )
    from .no_response_error import NoResponseError
    from .patch_v2_lists_list_entries_entry_id_op import (
        PatchV2ListsListEntriesEntryIDImmutableValueError,
        PatchV2ListsListEntriesEntryIDImmutableValueErrorData,
        PatchV2ListsListEntriesEntryIDNotFoundError,
        PatchV2ListsListEntriesEntryIDNotFoundErrorData,
    )
    from .patch_v2_lists_list_op import (
        PatchV2ListsListInvalidRequestError,
        PatchV2ListsListInvalidRequestErrorData,
        PatchV2ListsListNotFoundError,
        PatchV2ListsListNotFoundErrorData,
    )
    from .patch_v2_objects_object_op import (
        PatchV2ObjectsObjectNotFoundError,
        PatchV2ObjectsObjectNotFoundErrorData,
        PatchV2ObjectsObjectSlugConflictError,
        PatchV2ObjectsObjectSlugConflictErrorData,
        PatchV2ObjectsObjectValidationTypeError,
        PatchV2ObjectsObjectValidationTypeErrorData,
    )
    from .patch_v2_objects_object_records_record_id_op import (
        PatchV2ObjectsObjectRecordsRecordIDMissingValueError,
        PatchV2ObjectsObjectRecordsRecordIDMissingValueErrorData,
        PatchV2ObjectsObjectRecordsRecordIDNotFoundError,
        PatchV2ObjectsObjectRecordsRecordIDNotFoundErrorData,
    )
    from .patch_v2_target_identifier_attributes_attribute_op import (
        PatchV2TargetIdentifierAttributesAttributeNotFoundError,
        PatchV2TargetIdentifierAttributesAttributeNotFoundErrorData,
        SystemEditUnauthorizedError,
        SystemEditUnauthorizedErrorData,
    )
    from .patch_v2_target_identifier_attributes_attribute_options_option_op import (
        PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError,
        PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestErrorData,
        PatchV2TargetIdentifierAttributesAttributeOptionsOptionNotFoundError,
        PatchV2TargetIdentifierAttributesAttributeOptionsOptionNotFoundErrorData,
        PatchV2TargetIdentifierAttributesAttributeOptionsOptionSlugConflictError,
        PatchV2TargetIdentifierAttributesAttributeOptionsOptionSlugConflictErrorData,
    )
    from .patch_v2_target_identifier_attributes_attribute_statuses_status_op import (
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError,
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData,
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundError,
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData,
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictError,
        PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData,
    )
    from .patch_v2_tasks_task_id_op import (
        PatchV2TasksTaskIDNotFoundError,
        PatchV2TasksTaskIDNotFoundErrorData,
        PatchV2TasksTaskIDValidationTypeError,
        PatchV2TasksTaskIDValidationTypeErrorData,
    )
    from .patch_v2_webhooks_webhook_id_op import (
        PatchV2WebhooksWebhookIDNotFoundError,
        PatchV2WebhooksWebhookIDNotFoundErrorData,
    )
    from .post_v2_commentsop import (
        PostV2CommentsInvalidRequestError,
        PostV2CommentsInvalidRequestErrorData,
    )
    from .post_v2_lists_list_entries_queryop import (
        PostV2ListsListEntriesQueryNotFoundError,
        PostV2ListsListEntriesQueryNotFoundErrorData,
    )
    from .post_v2_lists_list_entriesop import (
        PostV2ListsListEntriesInvalidRequestError,
        PostV2ListsListEntriesInvalidRequestErrorData,
        PostV2ListsListEntriesNotFoundError,
        PostV2ListsListEntriesNotFoundErrorData,
    )
    from .post_v2_listsop import (
        BillingError,
        BillingErrorData,
        PostV2ListsInvalidRequestError,
        PostV2ListsInvalidRequestErrorData,
        PostV2ListsNotFoundError,
        PostV2ListsNotFoundErrorData,
        PostV2ListsSlugConflictError,
        PostV2ListsSlugConflictErrorData,
    )
    from .post_v2_meetings_meeting_id_call_recordingsop import (
        AuthError,
        AuthErrorData,
        PostV2MeetingsMeetingIDCallRecordingsNotFoundError,
        PostV2MeetingsMeetingIDCallRecordingsNotFoundErrorData,
        PostV2MeetingsMeetingIDCallRecordingsValidationTypeError,
        PostV2MeetingsMeetingIDCallRecordingsValidationTypeErrorData,
    )
    from .post_v2_meetingsop import (
        PostV2MeetingsValidationTypeError,
        PostV2MeetingsValidationTypeErrorData,
    )
    from .post_v2_notesop import (
        PostV2NotesNotFoundError,
        PostV2NotesNotFoundErrorData,
        PostV2NotesValidationTypeError,
        PostV2NotesValidationTypeErrorData,
    )
    from .post_v2_objects_object_records_queryop import (
        FilterError,
        FilterErrorData,
        PostV2ObjectsObjectRecordsQueryNotFoundError,
        PostV2ObjectsObjectRecordsQueryNotFoundErrorData,
    )
    from .post_v2_objects_object_recordsop import (
        PostV2ObjectsObjectRecordsInvalidRequestError,
        PostV2ObjectsObjectRecordsInvalidRequestErrorData,
        PostV2ObjectsObjectRecordsNotFoundError,
        PostV2ObjectsObjectRecordsNotFoundErrorData,
    )
    from .post_v2_objects_records_searchop import (
        PostV2ObjectsRecordsSearchInvalidRequestError,
        PostV2ObjectsRecordsSearchInvalidRequestErrorData,
    )
    from .post_v2_objectsop import (
        PostV2ObjectsSlugConflictError,
        PostV2ObjectsSlugConflictErrorData,
    )
    from .post_v2_target_identifier_attributes_attribute_optionsop import (
        PostV2TargetIdentifierAttributesAttributeOptionsNotFoundError,
        PostV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData,
        PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError,
        PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData,
        PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError,
        PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData,
    )
    from .post_v2_target_identifier_attributes_attribute_statusesop import (
        PostV2TargetIdentifierAttributesAttributeStatusesNotFoundError,
        PostV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData,
        PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError,
        PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictErrorData,
        PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError,
        PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeErrorData,
    )
    from .post_v2_target_identifier_attributesop import (
        PostV2TargetIdentifierAttributesNotFoundError,
        PostV2TargetIdentifierAttributesNotFoundErrorData,
        PostV2TargetIdentifierAttributesSlugConflictError,
        PostV2TargetIdentifierAttributesSlugConflictErrorData,
        PostV2TargetIdentifierAttributesValidationTypeError,
        PostV2TargetIdentifierAttributesValidationTypeErrorData,
    )
    from .post_v2_tasksop import (
        PostV2TasksNotFoundError,
        PostV2TasksNotFoundErrorData,
        PostV2TasksValidationTypeError,
        PostV2TasksValidationTypeErrorData,
    )
    from .post_v2_webhooksop import (
        PostV2WebhooksValidationTypeError,
        PostV2WebhooksValidationTypeErrorData,
    )
    from .put_v2_lists_list_entries_entry_id_op import (
        PutV2ListsListEntriesEntryIDImmutableValueError,
        PutV2ListsListEntriesEntryIDImmutableValueErrorData,
        PutV2ListsListEntriesEntryIDNotFoundError,
        PutV2ListsListEntriesEntryIDNotFoundErrorData,
    )
    from .put_v2_lists_list_entriesop import (
        MultipleMatchResultsError,
        MultipleMatchResultsErrorData,
        PutV2ListsListEntriesNotFoundError,
        PutV2ListsListEntriesNotFoundErrorData,
    )
    from .put_v2_objects_object_records_record_id_op import (
        PutV2ObjectsObjectRecordsRecordIDMissingValueError,
        PutV2ObjectsObjectRecordsRecordIDMissingValueErrorData,
        PutV2ObjectsObjectRecordsRecordIDNotFoundError,
        PutV2ObjectsObjectRecordsRecordIDNotFoundErrorData,
    )
    from .put_v2_objects_object_recordsop import (
        PutV2ObjectsObjectRecordsInvalidRequestError,
        PutV2ObjectsObjectRecordsInvalidRequestErrorData,
        PutV2ObjectsObjectRecordsNotFoundError,
        PutV2ObjectsObjectRecordsNotFoundErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .sdkdefaulterror import SDKDefaultError

__all__ = [
    "AuthError",
    "AuthErrorData",
    "BillingError",
    "BillingErrorData",
    "DeleteV2CommentsCommentIDNotFoundError",
    "DeleteV2CommentsCommentIDNotFoundErrorData",
    "DeleteV2FilesFileIDNotFoundError",
    "DeleteV2FilesFileIDNotFoundErrorData",
    "DeleteV2ListsListEntriesEntryIDNotFoundError",
    "DeleteV2ListsListEntriesEntryIDNotFoundErrorData",
    "DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundError",
    "DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData",
    "DeleteV2NotesNoteIDNotFoundError",
    "DeleteV2NotesNoteIDNotFoundErrorData",
    "DeleteV2ObjectsObjectRecordsRecordIDNotFoundError",
    "DeleteV2ObjectsObjectRecordsRecordIDNotFoundErrorData",
    "DeleteV2TasksTaskIDNotFoundError",
    "DeleteV2TasksTaskIDNotFoundErrorData",
    "DeleteV2WebhooksWebhookIDNotFoundError",
    "DeleteV2WebhooksWebhookIDNotFoundErrorData",
    "FilterError",
    "FilterErrorData",
    "GetV2CommentsCommentIDNotFoundError",
    "GetV2CommentsCommentIDNotFoundErrorData",
    "GetV2FilesFileIDNotFoundError",
    "GetV2FilesFileIDNotFoundErrorData",
    "GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundError",
    "GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundErrorData",
    "GetV2ListsListEntriesEntryIDNotFoundError",
    "GetV2ListsListEntriesEntryIDNotFoundErrorData",
    "GetV2ListsListNotFoundError",
    "GetV2ListsListNotFoundErrorData",
    "GetV2ListsListViewsNotFoundError",
    "GetV2ListsListViewsNotFoundErrorData",
    "GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundError",
    "GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData",
    "GetV2MeetingsMeetingIDNotFoundError",
    "GetV2MeetingsMeetingIDNotFoundErrorData",
    "GetV2NotesNotFoundError",
    "GetV2NotesNotFoundErrorData",
    "GetV2NotesNoteIDNotFoundError",
    "GetV2NotesNoteIDNotFoundErrorData",
    "GetV2ObjectsObjectNotFoundError",
    "GetV2ObjectsObjectNotFoundErrorData",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundError",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundErrorData",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeError",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeErrorData",
    "GetV2ObjectsObjectRecordsRecordIDNotFoundError",
    "GetV2ObjectsObjectRecordsRecordIDNotFoundErrorData",
    "GetV2ObjectsObjectViewsNotFoundError",
    "GetV2ObjectsObjectViewsNotFoundErrorData",
    "GetV2TargetIdentifierAttributesAttributeNotFoundError",
    "GetV2TargetIdentifierAttributesAttributeNotFoundErrorData",
    "GetV2TargetIdentifierAttributesAttributeOptionsNotFoundError",
    "GetV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData",
    "GetV2TargetIdentifierAttributesAttributeStatusesNotFoundError",
    "GetV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData",
    "GetV2TasksTaskIDNotFoundError",
    "GetV2TasksTaskIDNotFoundErrorData",
    "GetV2ThreadsThreadIDNotFoundError",
    "GetV2ThreadsThreadIDNotFoundErrorData",
    "GetV2WebhooksWebhookIDNotFoundError",
    "GetV2WebhooksWebhookIDNotFoundErrorData",
    "GetV2WorkspaceMembersWorkspaceMemberIDNotFoundError",
    "GetV2WorkspaceMembersWorkspaceMemberIDNotFoundErrorData",
    "MultipleMatchResultsError",
    "MultipleMatchResultsErrorData",
    "NoResponseError",
    "PatchV2ListsListEntriesEntryIDImmutableValueError",
    "PatchV2ListsListEntriesEntryIDImmutableValueErrorData",
    "PatchV2ListsListEntriesEntryIDNotFoundError",
    "PatchV2ListsListEntriesEntryIDNotFoundErrorData",
    "PatchV2ListsListInvalidRequestError",
    "PatchV2ListsListInvalidRequestErrorData",
    "PatchV2ListsListNotFoundError",
    "PatchV2ListsListNotFoundErrorData",
    "PatchV2ObjectsObjectNotFoundError",
    "PatchV2ObjectsObjectNotFoundErrorData",
    "PatchV2ObjectsObjectRecordsRecordIDMissingValueError",
    "PatchV2ObjectsObjectRecordsRecordIDMissingValueErrorData",
    "PatchV2ObjectsObjectRecordsRecordIDNotFoundError",
    "PatchV2ObjectsObjectRecordsRecordIDNotFoundErrorData",
    "PatchV2ObjectsObjectSlugConflictError",
    "PatchV2ObjectsObjectSlugConflictErrorData",
    "PatchV2ObjectsObjectValidationTypeError",
    "PatchV2ObjectsObjectValidationTypeErrorData",
    "PatchV2TargetIdentifierAttributesAttributeNotFoundError",
    "PatchV2TargetIdentifierAttributesAttributeNotFoundErrorData",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestErrorData",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionNotFoundError",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionNotFoundErrorData",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionSlugConflictError",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionSlugConflictErrorData",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundError",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictError",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData",
    "PatchV2TasksTaskIDNotFoundError",
    "PatchV2TasksTaskIDNotFoundErrorData",
    "PatchV2TasksTaskIDValidationTypeError",
    "PatchV2TasksTaskIDValidationTypeErrorData",
    "PatchV2WebhooksWebhookIDNotFoundError",
    "PatchV2WebhooksWebhookIDNotFoundErrorData",
    "PostV2CommentsInvalidRequestError",
    "PostV2CommentsInvalidRequestErrorData",
    "PostV2ListsInvalidRequestError",
    "PostV2ListsInvalidRequestErrorData",
    "PostV2ListsListEntriesInvalidRequestError",
    "PostV2ListsListEntriesInvalidRequestErrorData",
    "PostV2ListsListEntriesNotFoundError",
    "PostV2ListsListEntriesNotFoundErrorData",
    "PostV2ListsListEntriesQueryNotFoundError",
    "PostV2ListsListEntriesQueryNotFoundErrorData",
    "PostV2ListsNotFoundError",
    "PostV2ListsNotFoundErrorData",
    "PostV2ListsSlugConflictError",
    "PostV2ListsSlugConflictErrorData",
    "PostV2MeetingsMeetingIDCallRecordingsNotFoundError",
    "PostV2MeetingsMeetingIDCallRecordingsNotFoundErrorData",
    "PostV2MeetingsMeetingIDCallRecordingsValidationTypeError",
    "PostV2MeetingsMeetingIDCallRecordingsValidationTypeErrorData",
    "PostV2MeetingsValidationTypeError",
    "PostV2MeetingsValidationTypeErrorData",
    "PostV2NotesNotFoundError",
    "PostV2NotesNotFoundErrorData",
    "PostV2NotesValidationTypeError",
    "PostV2NotesValidationTypeErrorData",
    "PostV2ObjectsObjectRecordsInvalidRequestError",
    "PostV2ObjectsObjectRecordsInvalidRequestErrorData",
    "PostV2ObjectsObjectRecordsNotFoundError",
    "PostV2ObjectsObjectRecordsNotFoundErrorData",
    "PostV2ObjectsObjectRecordsQueryNotFoundError",
    "PostV2ObjectsObjectRecordsQueryNotFoundErrorData",
    "PostV2ObjectsRecordsSearchInvalidRequestError",
    "PostV2ObjectsRecordsSearchInvalidRequestErrorData",
    "PostV2ObjectsSlugConflictError",
    "PostV2ObjectsSlugConflictErrorData",
    "PostV2TargetIdentifierAttributesAttributeOptionsNotFoundError",
    "PostV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData",
    "PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError",
    "PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData",
    "PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError",
    "PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData",
    "PostV2TargetIdentifierAttributesAttributeStatusesNotFoundError",
    "PostV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData",
    "PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError",
    "PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictErrorData",
    "PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError",
    "PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeErrorData",
    "PostV2TargetIdentifierAttributesNotFoundError",
    "PostV2TargetIdentifierAttributesNotFoundErrorData",
    "PostV2TargetIdentifierAttributesSlugConflictError",
    "PostV2TargetIdentifierAttributesSlugConflictErrorData",
    "PostV2TargetIdentifierAttributesValidationTypeError",
    "PostV2TargetIdentifierAttributesValidationTypeErrorData",
    "PostV2TasksNotFoundError",
    "PostV2TasksNotFoundErrorData",
    "PostV2TasksValidationTypeError",
    "PostV2TasksValidationTypeErrorData",
    "PostV2WebhooksValidationTypeError",
    "PostV2WebhooksValidationTypeErrorData",
    "PutV2ListsListEntriesEntryIDImmutableValueError",
    "PutV2ListsListEntriesEntryIDImmutableValueErrorData",
    "PutV2ListsListEntriesEntryIDNotFoundError",
    "PutV2ListsListEntriesEntryIDNotFoundErrorData",
    "PutV2ListsListEntriesNotFoundError",
    "PutV2ListsListEntriesNotFoundErrorData",
    "PutV2ObjectsObjectRecordsInvalidRequestError",
    "PutV2ObjectsObjectRecordsInvalidRequestErrorData",
    "PutV2ObjectsObjectRecordsNotFoundError",
    "PutV2ObjectsObjectRecordsNotFoundErrorData",
    "PutV2ObjectsObjectRecordsRecordIDMissingValueError",
    "PutV2ObjectsObjectRecordsRecordIDMissingValueErrorData",
    "PutV2ObjectsObjectRecordsRecordIDNotFoundError",
    "PutV2ObjectsObjectRecordsRecordIDNotFoundErrorData",
    "ResponseValidationError",
    "SDKDefaultError",
    "SDKError",
    "SystemEditUnauthorizedError",
    "SystemEditUnauthorizedErrorData",
]

_dynamic_imports: dict[str, str] = {
    "DeleteV2CommentsCommentIDNotFoundError": ".delete_v2_comments_comment_id_op",
    "DeleteV2CommentsCommentIDNotFoundErrorData": ".delete_v2_comments_comment_id_op",
    "DeleteV2FilesFileIDNotFoundError": ".delete_v2_files_file_id_op",
    "DeleteV2FilesFileIDNotFoundErrorData": ".delete_v2_files_file_id_op",
    "DeleteV2ListsListEntriesEntryIDNotFoundError": ".delete_v2_lists_list_entries_entry_id_op",
    "DeleteV2ListsListEntriesEntryIDNotFoundErrorData": ".delete_v2_lists_list_entries_entry_id_op",
    "DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundError": ".delete_v2_meetings_meeting_id_call_recordings_call_recording_id_op",
    "DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData": ".delete_v2_meetings_meeting_id_call_recordings_call_recording_id_op",
    "DeleteV2NotesNoteIDNotFoundError": ".delete_v2_notes_note_id_op",
    "DeleteV2NotesNoteIDNotFoundErrorData": ".delete_v2_notes_note_id_op",
    "DeleteV2ObjectsObjectRecordsRecordIDNotFoundError": ".delete_v2_objects_object_records_record_id_op",
    "DeleteV2ObjectsObjectRecordsRecordIDNotFoundErrorData": ".delete_v2_objects_object_records_record_id_op",
    "DeleteV2TasksTaskIDNotFoundError": ".delete_v2_tasks_task_id_op",
    "DeleteV2TasksTaskIDNotFoundErrorData": ".delete_v2_tasks_task_id_op",
    "DeleteV2WebhooksWebhookIDNotFoundError": ".delete_v2_webhooks_webhook_id_op",
    "DeleteV2WebhooksWebhookIDNotFoundErrorData": ".delete_v2_webhooks_webhook_id_op",
    "GetV2CommentsCommentIDNotFoundError": ".get_v2_comments_comment_id_op",
    "GetV2CommentsCommentIDNotFoundErrorData": ".get_v2_comments_comment_id_op",
    "GetV2FilesFileIDNotFoundError": ".get_v2_files_file_id_op",
    "GetV2FilesFileIDNotFoundErrorData": ".get_v2_files_file_id_op",
    "GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundError": ".get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop",
    "GetV2ListsListEntriesEntryIDAttributesAttributeValuesNotFoundErrorData": ".get_v2_lists_list_entries_entry_id_attributes_attribute_valuesop",
    "GetV2ListsListEntriesEntryIDNotFoundError": ".get_v2_lists_list_entries_entry_id_op",
    "GetV2ListsListEntriesEntryIDNotFoundErrorData": ".get_v2_lists_list_entries_entry_id_op",
    "GetV2ListsListNotFoundError": ".get_v2_lists_list_op",
    "GetV2ListsListNotFoundErrorData": ".get_v2_lists_list_op",
    "GetV2ListsListViewsNotFoundError": ".get_v2_lists_list_viewsop",
    "GetV2ListsListViewsNotFoundErrorData": ".get_v2_lists_list_viewsop",
    "GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundError": ".get_v2_meetings_meeting_id_call_recordings_call_recording_id_op",
    "GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData": ".get_v2_meetings_meeting_id_call_recordings_call_recording_id_op",
    "GetV2MeetingsMeetingIDNotFoundError": ".get_v2_meetings_meeting_id_op",
    "GetV2MeetingsMeetingIDNotFoundErrorData": ".get_v2_meetings_meeting_id_op",
    "GetV2NotesNoteIDNotFoundError": ".get_v2_notes_note_id_op",
    "GetV2NotesNoteIDNotFoundErrorData": ".get_v2_notes_note_id_op",
    "GetV2NotesNotFoundError": ".get_v2_notesop",
    "GetV2NotesNotFoundErrorData": ".get_v2_notesop",
    "GetV2ObjectsObjectNotFoundError": ".get_v2_objects_object_op",
    "GetV2ObjectsObjectNotFoundErrorData": ".get_v2_objects_object_op",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundError": ".get_v2_objects_object_records_record_id_attributes_attribute_valuesop",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesNotFoundErrorData": ".get_v2_objects_object_records_record_id_attributes_attribute_valuesop",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeError": ".get_v2_objects_object_records_record_id_attributes_attribute_valuesop",
    "GetV2ObjectsObjectRecordsRecordIDAttributesAttributeValuesValidationTypeErrorData": ".get_v2_objects_object_records_record_id_attributes_attribute_valuesop",
    "GetV2ObjectsObjectRecordsRecordIDNotFoundError": ".get_v2_objects_object_records_record_id_op",
    "GetV2ObjectsObjectRecordsRecordIDNotFoundErrorData": ".get_v2_objects_object_records_record_id_op",
    "GetV2ObjectsObjectViewsNotFoundError": ".get_v2_objects_object_viewsop",
    "GetV2ObjectsObjectViewsNotFoundErrorData": ".get_v2_objects_object_viewsop",
    "GetV2TargetIdentifierAttributesAttributeNotFoundError": ".get_v2_target_identifier_attributes_attribute_op",
    "GetV2TargetIdentifierAttributesAttributeNotFoundErrorData": ".get_v2_target_identifier_attributes_attribute_op",
    "GetV2TargetIdentifierAttributesAttributeOptionsNotFoundError": ".get_v2_target_identifier_attributes_attribute_optionsop",
    "GetV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData": ".get_v2_target_identifier_attributes_attribute_optionsop",
    "GetV2TargetIdentifierAttributesAttributeStatusesNotFoundError": ".get_v2_target_identifier_attributes_attribute_statusesop",
    "GetV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData": ".get_v2_target_identifier_attributes_attribute_statusesop",
    "GetV2TasksTaskIDNotFoundError": ".get_v2_tasks_task_id_op",
    "GetV2TasksTaskIDNotFoundErrorData": ".get_v2_tasks_task_id_op",
    "GetV2ThreadsThreadIDNotFoundError": ".get_v2_threads_thread_id_op",
    "GetV2ThreadsThreadIDNotFoundErrorData": ".get_v2_threads_thread_id_op",
    "GetV2WebhooksWebhookIDNotFoundError": ".get_v2_webhooks_webhook_id_op",
    "GetV2WebhooksWebhookIDNotFoundErrorData": ".get_v2_webhooks_webhook_id_op",
    "GetV2WorkspaceMembersWorkspaceMemberIDNotFoundError": ".get_v2_workspace_members_workspace_member_id_op",
    "GetV2WorkspaceMembersWorkspaceMemberIDNotFoundErrorData": ".get_v2_workspace_members_workspace_member_id_op",
    "NoResponseError": ".no_response_error",
    "PatchV2ListsListEntriesEntryIDImmutableValueError": ".patch_v2_lists_list_entries_entry_id_op",
    "PatchV2ListsListEntriesEntryIDImmutableValueErrorData": ".patch_v2_lists_list_entries_entry_id_op",
    "PatchV2ListsListEntriesEntryIDNotFoundError": ".patch_v2_lists_list_entries_entry_id_op",
    "PatchV2ListsListEntriesEntryIDNotFoundErrorData": ".patch_v2_lists_list_entries_entry_id_op",
    "PatchV2ListsListInvalidRequestError": ".patch_v2_lists_list_op",
    "PatchV2ListsListInvalidRequestErrorData": ".patch_v2_lists_list_op",
    "PatchV2ListsListNotFoundError": ".patch_v2_lists_list_op",
    "PatchV2ListsListNotFoundErrorData": ".patch_v2_lists_list_op",
    "PatchV2ObjectsObjectNotFoundError": ".patch_v2_objects_object_op",
    "PatchV2ObjectsObjectNotFoundErrorData": ".patch_v2_objects_object_op",
    "PatchV2ObjectsObjectSlugConflictError": ".patch_v2_objects_object_op",
    "PatchV2ObjectsObjectSlugConflictErrorData": ".patch_v2_objects_object_op",
    "PatchV2ObjectsObjectValidationTypeError": ".patch_v2_objects_object_op",
    "PatchV2ObjectsObjectValidationTypeErrorData": ".patch_v2_objects_object_op",
    "PatchV2ObjectsObjectRecordsRecordIDMissingValueError": ".patch_v2_objects_object_records_record_id_op",
    "PatchV2ObjectsObjectRecordsRecordIDMissingValueErrorData": ".patch_v2_objects_object_records_record_id_op",
    "PatchV2ObjectsObjectRecordsRecordIDNotFoundError": ".patch_v2_objects_object_records_record_id_op",
    "PatchV2ObjectsObjectRecordsRecordIDNotFoundErrorData": ".patch_v2_objects_object_records_record_id_op",
    "PatchV2TargetIdentifierAttributesAttributeNotFoundError": ".patch_v2_target_identifier_attributes_attribute_op",
    "PatchV2TargetIdentifierAttributesAttributeNotFoundErrorData": ".patch_v2_target_identifier_attributes_attribute_op",
    "SystemEditUnauthorizedError": ".patch_v2_target_identifier_attributes_attribute_op",
    "SystemEditUnauthorizedErrorData": ".patch_v2_target_identifier_attributes_attribute_op",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError": ".patch_v2_target_identifier_attributes_attribute_options_option_op",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestErrorData": ".patch_v2_target_identifier_attributes_attribute_options_option_op",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionNotFoundError": ".patch_v2_target_identifier_attributes_attribute_options_option_op",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionNotFoundErrorData": ".patch_v2_target_identifier_attributes_attribute_options_option_op",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionSlugConflictError": ".patch_v2_target_identifier_attributes_attribute_options_option_op",
    "PatchV2TargetIdentifierAttributesAttributeOptionsOptionSlugConflictErrorData": ".patch_v2_target_identifier_attributes_attribute_options_option_op",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError": ".patch_v2_target_identifier_attributes_attribute_statuses_status_op",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData": ".patch_v2_target_identifier_attributes_attribute_statuses_status_op",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundError": ".patch_v2_target_identifier_attributes_attribute_statuses_status_op",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusNotFoundErrorData": ".patch_v2_target_identifier_attributes_attribute_statuses_status_op",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictError": ".patch_v2_target_identifier_attributes_attribute_statuses_status_op",
    "PatchV2TargetIdentifierAttributesAttributeStatusesStatusSlugConflictErrorData": ".patch_v2_target_identifier_attributes_attribute_statuses_status_op",
    "PatchV2TasksTaskIDNotFoundError": ".patch_v2_tasks_task_id_op",
    "PatchV2TasksTaskIDNotFoundErrorData": ".patch_v2_tasks_task_id_op",
    "PatchV2TasksTaskIDValidationTypeError": ".patch_v2_tasks_task_id_op",
    "PatchV2TasksTaskIDValidationTypeErrorData": ".patch_v2_tasks_task_id_op",
    "PatchV2WebhooksWebhookIDNotFoundError": ".patch_v2_webhooks_webhook_id_op",
    "PatchV2WebhooksWebhookIDNotFoundErrorData": ".patch_v2_webhooks_webhook_id_op",
    "PostV2CommentsInvalidRequestError": ".post_v2_commentsop",
    "PostV2CommentsInvalidRequestErrorData": ".post_v2_commentsop",
    "PostV2ListsListEntriesQueryNotFoundError": ".post_v2_lists_list_entries_queryop",
    "PostV2ListsListEntriesQueryNotFoundErrorData": ".post_v2_lists_list_entries_queryop",
    "PostV2ListsListEntriesInvalidRequestError": ".post_v2_lists_list_entriesop",
    "PostV2ListsListEntriesInvalidRequestErrorData": ".post_v2_lists_list_entriesop",
    "PostV2ListsListEntriesNotFoundError": ".post_v2_lists_list_entriesop",
    "PostV2ListsListEntriesNotFoundErrorData": ".post_v2_lists_list_entriesop",
    "BillingError": ".post_v2_listsop",
    "BillingErrorData": ".post_v2_listsop",
    "PostV2ListsInvalidRequestError": ".post_v2_listsop",
    "PostV2ListsInvalidRequestErrorData": ".post_v2_listsop",
    "PostV2ListsNotFoundError": ".post_v2_listsop",
    "PostV2ListsNotFoundErrorData": ".post_v2_listsop",
    "PostV2ListsSlugConflictError": ".post_v2_listsop",
    "PostV2ListsSlugConflictErrorData": ".post_v2_listsop",
    "AuthError": ".post_v2_meetings_meeting_id_call_recordingsop",
    "AuthErrorData": ".post_v2_meetings_meeting_id_call_recordingsop",
    "PostV2MeetingsMeetingIDCallRecordingsNotFoundError": ".post_v2_meetings_meeting_id_call_recordingsop",
    "PostV2MeetingsMeetingIDCallRecordingsNotFoundErrorData": ".post_v2_meetings_meeting_id_call_recordingsop",
    "PostV2MeetingsMeetingIDCallRecordingsValidationTypeError": ".post_v2_meetings_meeting_id_call_recordingsop",
    "PostV2MeetingsMeetingIDCallRecordingsValidationTypeErrorData": ".post_v2_meetings_meeting_id_call_recordingsop",
    "PostV2MeetingsValidationTypeError": ".post_v2_meetingsop",
    "PostV2MeetingsValidationTypeErrorData": ".post_v2_meetingsop",
    "PostV2NotesNotFoundError": ".post_v2_notesop",
    "PostV2NotesNotFoundErrorData": ".post_v2_notesop",
    "PostV2NotesValidationTypeError": ".post_v2_notesop",
    "PostV2NotesValidationTypeErrorData": ".post_v2_notesop",
    "FilterError": ".post_v2_objects_object_records_queryop",
    "FilterErrorData": ".post_v2_objects_object_records_queryop",
    "PostV2ObjectsObjectRecordsQueryNotFoundError": ".post_v2_objects_object_records_queryop",
    "PostV2ObjectsObjectRecordsQueryNotFoundErrorData": ".post_v2_objects_object_records_queryop",
    "PostV2ObjectsObjectRecordsInvalidRequestError": ".post_v2_objects_object_recordsop",
    "PostV2ObjectsObjectRecordsInvalidRequestErrorData": ".post_v2_objects_object_recordsop",
    "PostV2ObjectsObjectRecordsNotFoundError": ".post_v2_objects_object_recordsop",
    "PostV2ObjectsObjectRecordsNotFoundErrorData": ".post_v2_objects_object_recordsop",
    "PostV2ObjectsRecordsSearchInvalidRequestError": ".post_v2_objects_records_searchop",
    "PostV2ObjectsRecordsSearchInvalidRequestErrorData": ".post_v2_objects_records_searchop",
    "PostV2ObjectsSlugConflictError": ".post_v2_objectsop",
    "PostV2ObjectsSlugConflictErrorData": ".post_v2_objectsop",
    "PostV2TargetIdentifierAttributesAttributeOptionsNotFoundError": ".post_v2_target_identifier_attributes_attribute_optionsop",
    "PostV2TargetIdentifierAttributesAttributeOptionsNotFoundErrorData": ".post_v2_target_identifier_attributes_attribute_optionsop",
    "PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError": ".post_v2_target_identifier_attributes_attribute_optionsop",
    "PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData": ".post_v2_target_identifier_attributes_attribute_optionsop",
    "PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError": ".post_v2_target_identifier_attributes_attribute_optionsop",
    "PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData": ".post_v2_target_identifier_attributes_attribute_optionsop",
    "PostV2TargetIdentifierAttributesAttributeStatusesNotFoundError": ".post_v2_target_identifier_attributes_attribute_statusesop",
    "PostV2TargetIdentifierAttributesAttributeStatusesNotFoundErrorData": ".post_v2_target_identifier_attributes_attribute_statusesop",
    "PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError": ".post_v2_target_identifier_attributes_attribute_statusesop",
    "PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictErrorData": ".post_v2_target_identifier_attributes_attribute_statusesop",
    "PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError": ".post_v2_target_identifier_attributes_attribute_statusesop",
    "PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeErrorData": ".post_v2_target_identifier_attributes_attribute_statusesop",
    "PostV2TargetIdentifierAttributesNotFoundError": ".post_v2_target_identifier_attributesop",
    "PostV2TargetIdentifierAttributesNotFoundErrorData": ".post_v2_target_identifier_attributesop",
    "PostV2TargetIdentifierAttributesSlugConflictError": ".post_v2_target_identifier_attributesop",
    "PostV2TargetIdentifierAttributesSlugConflictErrorData": ".post_v2_target_identifier_attributesop",
    "PostV2TargetIdentifierAttributesValidationTypeError": ".post_v2_target_identifier_attributesop",
    "PostV2TargetIdentifierAttributesValidationTypeErrorData": ".post_v2_target_identifier_attributesop",
    "PostV2TasksNotFoundError": ".post_v2_tasksop",
    "PostV2TasksNotFoundErrorData": ".post_v2_tasksop",
    "PostV2TasksValidationTypeError": ".post_v2_tasksop",
    "PostV2TasksValidationTypeErrorData": ".post_v2_tasksop",
    "PostV2WebhooksValidationTypeError": ".post_v2_webhooksop",
    "PostV2WebhooksValidationTypeErrorData": ".post_v2_webhooksop",
    "PutV2ListsListEntriesEntryIDImmutableValueError": ".put_v2_lists_list_entries_entry_id_op",
    "PutV2ListsListEntriesEntryIDImmutableValueErrorData": ".put_v2_lists_list_entries_entry_id_op",
    "PutV2ListsListEntriesEntryIDNotFoundError": ".put_v2_lists_list_entries_entry_id_op",
    "PutV2ListsListEntriesEntryIDNotFoundErrorData": ".put_v2_lists_list_entries_entry_id_op",
    "MultipleMatchResultsError": ".put_v2_lists_list_entriesop",
    "MultipleMatchResultsErrorData": ".put_v2_lists_list_entriesop",
    "PutV2ListsListEntriesNotFoundError": ".put_v2_lists_list_entriesop",
    "PutV2ListsListEntriesNotFoundErrorData": ".put_v2_lists_list_entriesop",
    "PutV2ObjectsObjectRecordsRecordIDMissingValueError": ".put_v2_objects_object_records_record_id_op",
    "PutV2ObjectsObjectRecordsRecordIDMissingValueErrorData": ".put_v2_objects_object_records_record_id_op",
    "PutV2ObjectsObjectRecordsRecordIDNotFoundError": ".put_v2_objects_object_records_record_id_op",
    "PutV2ObjectsObjectRecordsRecordIDNotFoundErrorData": ".put_v2_objects_object_records_record_id_op",
    "PutV2ObjectsObjectRecordsInvalidRequestError": ".put_v2_objects_object_recordsop",
    "PutV2ObjectsObjectRecordsInvalidRequestErrorData": ".put_v2_objects_object_recordsop",
    "PutV2ObjectsObjectRecordsNotFoundError": ".put_v2_objects_object_recordsop",
    "PutV2ObjectsObjectRecordsNotFoundErrorData": ".put_v2_objects_object_recordsop",
    "ResponseValidationError": ".responsevalidationerror",
    "SDKDefaultError": ".sdkdefaulterror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
