"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    delete_v2_meetings_meeting_id_call_recordings_call_recording_id_op as models_delete_v2_meetings_meeting_id_call_recordings_call_recording_id_op,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData(
    BaseModel
):
    status_code: float
    type: models_delete_v2_meetings_meeting_id_call_recordings_call_recording_id_op.DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDType
    code: models_delete_v2_meetings_meeting_id_call_recordings_call_recording_id_op.DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDCode
    message: str


@dataclass(unsafe_hash=True)
class DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundError(SDKError):
    r"""Call recording not found"""

    data: DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData = (
        field(hash=False)
    )

    def __init__(
        self,
        data: DeleteV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
