"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import post_v2_files_uploadop as models_post_v2_files_uploadop
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PostV2FilesUploadAuthErrorData(BaseModel):
    status_code: float
    type: models_post_v2_files_uploadop.PostV2FilesUploadType
    code: models_post_v2_files_uploadop.PostV2FilesUploadCodeUnion
    message: str


@dataclass(unsafe_hash=True)
class PostV2FilesUploadAuthError(SDKError):
    r"""Forbidden"""

    data: PostV2FilesUploadAuthErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2FilesUploadAuthErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
