"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import (
    post_v2_objects_object_records_queryop as models_post_v2_objects_object_records_queryop,
)
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PostV2ObjectsObjectRecordsQueryNotFoundErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objects_object_records_queryop.PostV2ObjectsObjectRecordsQueryNotFoundType
    code: models_post_v2_objects_object_records_queryop.PostV2ObjectsObjectRecordsQueryNotFoundCode
    message: str


@dataclass(unsafe_hash=True)
class PostV2ObjectsObjectRecordsQueryNotFoundError(SDKError):
    r"""Not Found"""

    data: PostV2ObjectsObjectRecordsQueryNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ObjectsObjectRecordsQueryNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PostV2ObjectsObjectRecordsQueryFilterErrorData(BaseModel):
    status_code: float
    type: models_post_v2_objects_object_records_queryop.PostV2ObjectsObjectRecordsQueryBadRequestType
    code: models_post_v2_objects_object_records_queryop.PostV2ObjectsObjectRecordsQueryCodeFilterError
    message: str


@dataclass(unsafe_hash=True)
class PostV2ObjectsObjectRecordsQueryFilterError(SDKError):
    r"""Bad Request"""

    data: PostV2ObjectsObjectRecordsQueryFilterErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2ObjectsObjectRecordsQueryFilterErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
