"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.errors import SDKError
from attio.models import post_v2_sqlop as models_post_v2_sqlop
from attio.types import BaseModel
from dataclasses import dataclass, field
import httpx
from typing import Optional


class PostV2SQLFilterErrorData(BaseModel):
    status_code: float
    type: models_post_v2_sqlop.PostV2SQLType
    code: models_post_v2_sqlop.PostV2SQLCode
    message: str


@dataclass(unsafe_hash=True)
class PostV2SQLFilterError(SDKError):
    r"""Bad Request"""

    data: PostV2SQLFilterErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV2SQLFilterErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
