workflowVersion: 1.0.0
sources:
    attio:
        inputs:
            - location: api-00.json
        overlays:
            - location: overlay.yaml
        output: api-01.json
        registry:
            location: registry.speakeasyapi.dev/elviskahoro/attio/attio
targets:
    attio:
        target: python
        source: attio
