"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
from typing import Literal
from typing_extensions import Annotated, TypedDict


class DeleteV2FilesFileIDRequestTypedDict(TypedDict):
    file_id: str


class DeleteV2FilesFileIDRequest(BaseModel):
    file_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


DeleteV2FilesFileIDType = Literal["invalid_request_error",]


DeleteV2FilesFileIDCode = Literal["not_found",]


class DeleteV2FilesFileIDResponseTypedDict(TypedDict):
    r"""Success"""


class DeleteV2FilesFileIDResponse(BaseModel):
    r"""Success"""
