"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteScimV2GroupsWorkspaceTeamIDRequestTypedDict(TypedDict):
    workspace_team_id: str
    r"""The ID of the SCIM group to delete."""


class DeleteScimV2GroupsWorkspaceTeamIDRequest(BaseModel):
    workspace_team_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the SCIM group to delete."""


class DeleteScimV2GroupsWorkspaceTeamIDResponseTypedDict(TypedDict):
    r"""No Content"""


class DeleteScimV2GroupsWorkspaceTeamIDResponse(BaseModel):
    r"""No Content"""
