"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteScimV2UsersUserIDRequestTypedDict(TypedDict):
    user_id: str
    r"""The ID of the SCIM user to delete."""


class DeleteScimV2UsersUserIDRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the SCIM user to delete."""


class DeleteScimV2UsersUserIDResponseTypedDict(TypedDict):
    r"""No Content"""


class DeleteScimV2UsersUserIDResponse(BaseModel):
    r"""No Content"""
