"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import TypedDict


class EmailIDTypedDict(TypedDict):
    workspace_id: str
    r"""The ID of the workspace the email belongs to."""
    mailbox_id: str
    r"""The ID of the mailbox this copy of the email was read from. A single email sent to several people in your workspace is stored once per mailbox; this endpoint returns one entry per email, so the returned `mailbox_id` identifies whichever copy was readable."""
    email_id: str
    r"""The ID of the Attio email."""


class EmailID(BaseModel):
    workspace_id: str
    r"""The ID of the workspace the email belongs to."""

    mailbox_id: str
    r"""The ID of the mailbox this copy of the email was read from. A single email sent to several people in your workspace is stored once per mailbox; this endpoint returns one entry per email, so the returned `mailbox_id` identifies whichever copy was readable."""

    email_id: str
    r"""The ID of the Attio email."""


Direction = Literal[
    "inbound",
    "outbound",
]
r"""Whether the email was sent from your workspace or received by it."""


Role = Literal[
    "from",
    "reply-to",
    "to",
    "cc",
    "bcc",
]
r"""The role this participant had on the email."""


class EmailParticipantTypedDict(TypedDict):
    role: Role
    r"""The role this participant had on the email."""
    email_address: str
    r"""The normalized email address of the participant."""
    email_domain: str
    r"""The domain of the participant's email address."""
    name: Nullable[str]
    r"""The participant's name as it appeared on the email, when the email provided one."""


class EmailParticipant(BaseModel):
    role: Role
    r"""The role this participant had on the email."""

    email_address: str
    r"""The normalized email address of the participant."""

    email_domain: str
    r"""The domain of the participant's email address."""

    name: Nullable[str]
    r"""The participant's name as it appeared on the email, when the email provided one."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class EmailLinkedRecordTypedDict(TypedDict):
    object_slug: str
    r"""The slug of the object the linked record belongs to."""
    object_id: str
    r"""The ID of the object the linked record belongs to."""
    record_id: str
    r"""The ID of the linked record."""


class EmailLinkedRecord(BaseModel):
    object_slug: str
    r"""The slug of the object the linked record belongs to."""

    object_id: str
    r"""The ID of the object the linked record belongs to."""

    record_id: str
    r"""The ID of the linked record."""


class EmailTypedDict(TypedDict):
    id: EmailIDTypedDict
    sent_at: str
    r"""Timestamp representing when the email was sent, taken from the email's own headers rather than from when Attio imported it."""
    direction: Direction
    r"""Whether the email was sent from your workspace or received by it."""
    subject_line: Nullable[str]
    r"""The subject line of the email. This is `null` when the email has no subject or is from a mailbox shared as metadata only."""
    participants: List[EmailParticipantTypedDict]
    r"""The participants on the email. Note that `bcc` participants are realistically only present on outbound email: inbound messages do not disclose the other recipients' blind copies, so an absent `bcc` participant is not evidence that there was none."""
    linked_records: List[EmailLinkedRecordTypedDict]
    r"""The person and company records whose email addresses or domains match this email's participants. Unlike meetings, this link is derived when you make the request rather than stored, so it reflects your records as they are now: creating a person record today will make older emails start reporting it."""


class Email(BaseModel):
    id: EmailID

    sent_at: str
    r"""Timestamp representing when the email was sent, taken from the email's own headers rather than from when Attio imported it."""

    direction: Direction
    r"""Whether the email was sent from your workspace or received by it."""

    subject_line: Nullable[str]
    r"""The subject line of the email. This is `null` when the email has no subject or is from a mailbox shared as metadata only."""

    participants: List[EmailParticipant]
    r"""The participants on the email. Note that `bcc` participants are realistically only present on outbound email: inbound messages do not disclose the other recipients' blind copies, so an absent `bcc` participant is not evidence that there was none."""

    linked_records: List[EmailLinkedRecord]
    r"""The person and company records whose email addresses or domains match this email's participants. Unlike meetings, this link is derived when you make the request rather than stored, so it reflects your records as they are now: creating a person record today will make older emails start reporting it."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
