"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal
from typing_extensions import NotRequired, TypedDict


class FolderIDTypedDict(TypedDict):
    workspace_id: str
    r"""The ID of the workspace the file belongs to."""
    file_id: str
    r"""The ID of the file entry."""


class FolderID(BaseModel):
    workspace_id: str
    r"""The ID of the workspace the file belongs to."""

    file_id: str
    r"""The ID of the file entry."""


FolderStorageProvider = Literal[
    "attio",
    "dropbox",
    "box",
    "google-drive",
    "microsoft-onedrive",
]
r"""The storage provider for this file entry."""


FolderType = Literal[
    "api-token",
    "workspace-member",
    "system",
    "app",
]
r"""The type of actor. [Read more information on actor types here](/docs/actors)."""


class FolderCreatedByActorTypedDict(TypedDict):
    r"""The actor that created this file entry."""

    id: NotRequired[Nullable[str]]
    r"""An ID to identify the actor."""
    type: NotRequired[Nullable[FolderType]]
    r"""The type of actor. [Read more information on actor types here](/docs/actors)."""


class FolderCreatedByActor(BaseModel):
    r"""The actor that created this file entry."""

    id: OptionalNullable[str] = UNSET
    r"""An ID to identify the actor."""

    type: OptionalNullable[FolderType] = UNSET
    r"""The type of actor. [Read more information on actor types here](/docs/actors)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type"])
        nullable_fields = set(["id", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


FolderFileType = Literal["folder",]
r"""The type of file entry."""


class FolderTypedDict(TypedDict):
    id: FolderIDTypedDict
    object_id: str
    r"""The ID of the object the record belongs to."""
    object_slug: str
    r"""The slug of the object the record belongs to."""
    record_id: str
    r"""The ID of the record the file is linked to."""
    storage_provider: FolderStorageProvider
    r"""The storage provider for this file entry."""
    created_by_actor: FolderCreatedByActorTypedDict
    r"""The actor that created this file entry."""
    created_at: str
    r"""Timestamp representing when the file entry was created."""
    file_type: FolderFileType
    r"""The type of file entry."""
    name: str
    r"""The name of the folder."""
    parent_folder_id: Nullable[str]
    r"""The ID of the parent folder, or null if this is a top-level folder."""


class Folder(BaseModel):
    id: FolderID

    object_id: str
    r"""The ID of the object the record belongs to."""

    object_slug: str
    r"""The slug of the object the record belongs to."""

    record_id: str
    r"""The ID of the record the file is linked to."""

    storage_provider: FolderStorageProvider
    r"""The storage provider for this file entry."""

    created_by_actor: FolderCreatedByActor
    r"""The actor that created this file entry."""

    created_at: str
    r"""Timestamp representing when the file entry was created."""

    file_type: FolderFileType
    r"""The type of file entry."""

    name: str
    r"""The name of the folder."""

    parent_folder_id: Nullable[str]
    r"""The ID of the parent folder, or null if this is a top-level folder."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
