"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
import pydantic
from typing import Any, List
from typing_extensions import Annotated, TypedDict


class GetScimV2SchemasResponseTypedDict(TypedDict):
    r"""Success"""

    schemas: List[str]
    total_results: float
    start_index: float
    items_per_page: float
    resources: List[Any]


class GetScimV2SchemasResponse(BaseModel):
    r"""Success"""

    schemas: List[str]

    total_results: Annotated[float, pydantic.Field(alias="totalResults")]

    start_index: Annotated[float, pydantic.Field(alias="startIndex")]

    items_per_page: Annotated[float, pydantic.Field(alias="itemsPerPage")]

    resources: Annotated[List[Any], pydantic.Field(alias="Resources")]


try:
    GetScimV2SchemasResponse.model_rebuild()
except NameError:
    pass
