"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connected_file import ConnectedFile, ConnectedFileTypedDict
from .connected_folder import ConnectedFolder, ConnectedFolderTypedDict
from .file import File, FileTypedDict
from attio.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from attio.utils import FieldMetadata, PathParamMetadata, get_discriminator
from pydantic import Discriminator, Tag, model_serializer
from typing import Literal, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class GetV2FilesFileIDRequestTypedDict(TypedDict):
    file_id: str


class GetV2FilesFileIDRequest(BaseModel):
    file_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetV2FilesFileIDNotFoundType = Literal["invalid_request_error",]


GetV2FilesFileIDCode = Literal["not_found",]


class GetV2FilesFileIDIDTypedDict(TypedDict):
    workspace_id: str
    r"""The ID of the workspace the file belongs to."""
    file_id: str
    r"""The ID of the file entry."""


class GetV2FilesFileIDID(BaseModel):
    workspace_id: str
    r"""The ID of the workspace the file belongs to."""

    file_id: str
    r"""The ID of the file entry."""


GetV2FilesFileIDStorageProvider = Literal[
    "attio",
    "dropbox",
    "box",
    "google-drive",
    "microsoft-onedrive",
]
r"""The storage provider for this file entry."""


GetV2FilesFileIDCreatedByActorType = Literal[
    "api-token",
    "workspace-member",
    "system",
    "app",
]
r"""The type of actor. [Read more information on actor types here](/docs/actors)."""


class GetV2FilesFileIDCreatedByActorTypedDict(TypedDict):
    r"""The actor that created this file entry."""

    id: NotRequired[Nullable[str]]
    r"""An ID to identify the actor."""
    type: NotRequired[Nullable[GetV2FilesFileIDCreatedByActorType]]
    r"""The type of actor. [Read more information on actor types here](/docs/actors)."""


class GetV2FilesFileIDCreatedByActor(BaseModel):
    r"""The actor that created this file entry."""

    id: OptionalNullable[str] = UNSET
    r"""An ID to identify the actor."""

    type: OptionalNullable[GetV2FilesFileIDCreatedByActorType] = UNSET
    r"""The type of actor. [Read more information on actor types here](/docs/actors)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type"])
        nullable_fields = set(["id", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


GetV2FilesFileIDFileType = Literal["folder",]
r"""The type of file entry."""


class GetV2FilesFileIDFolderTypedDict(TypedDict):
    id: GetV2FilesFileIDIDTypedDict
    object_id: str
    r"""The ID of the object the record belongs to."""
    object_slug: str
    r"""The slug of the object the record belongs to."""
    record_id: str
    r"""The ID of the record the file is linked to."""
    storage_provider: GetV2FilesFileIDStorageProvider
    r"""The storage provider for this file entry."""
    created_by_actor: GetV2FilesFileIDCreatedByActorTypedDict
    r"""The actor that created this file entry."""
    created_at: str
    r"""Timestamp representing when the file entry was created."""
    file_type: GetV2FilesFileIDFileType
    r"""The type of file entry."""
    name: str
    r"""The name of the folder."""
    parent_folder_id: Nullable[str]
    r"""The ID of the parent folder, or null if this is a top-level folder."""
    has_children: bool
    r"""Whether the folder contains any child entries."""


class GetV2FilesFileIDFolder(BaseModel):
    id: GetV2FilesFileIDID

    object_id: str
    r"""The ID of the object the record belongs to."""

    object_slug: str
    r"""The slug of the object the record belongs to."""

    record_id: str
    r"""The ID of the record the file is linked to."""

    storage_provider: GetV2FilesFileIDStorageProvider
    r"""The storage provider for this file entry."""

    created_by_actor: GetV2FilesFileIDCreatedByActor
    r"""The actor that created this file entry."""

    created_at: str
    r"""Timestamp representing when the file entry was created."""

    file_type: GetV2FilesFileIDFileType
    r"""The type of file entry."""

    name: str
    r"""The name of the folder."""

    parent_folder_id: Nullable[str]
    r"""The ID of the parent folder, or null if this is a top-level folder."""

    has_children: bool
    r"""Whether the folder contains any child entries."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


GetV2FilesFileIDDataTypedDict = TypeAliasType(
    "GetV2FilesFileIDDataTypedDict",
    Union[
        ConnectedFileTypedDict,
        ConnectedFolderTypedDict,
        GetV2FilesFileIDFolderTypedDict,
        FileTypedDict,
    ],
)


GetV2FilesFileIDData = Annotated[
    Union[
        Annotated[File, Tag("file")],
        Annotated[GetV2FilesFileIDFolder, Tag("folder")],
        Annotated[ConnectedFile, Tag("connected-file")],
        Annotated[ConnectedFolder, Tag("connected-folder")],
    ],
    Discriminator(lambda m: get_discriminator(m, "file_type", "file_type")),
]


class GetV2FilesFileIDResponseTypedDict(TypedDict):
    r"""Success"""

    data: GetV2FilesFileIDDataTypedDict


class GetV2FilesFileIDResponse(BaseModel):
    r"""Success"""

    data: GetV2FilesFileIDData
