"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .object_view import ObjectView, ObjectViewTypedDict
from attio.types import BaseModel, Nullable, UNSET_SENTINEL
from attio.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetV2ObjectsObjectViewsRequestTypedDict(TypedDict):
    object: str
    show_archived: NotRequired[bool]
    limit: NotRequired[int]
    cursor: NotRequired[str]


class GetV2ObjectsObjectViewsRequest(BaseModel):
    object: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    show_archived: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 500

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["show_archived", "limit", "cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetV2ObjectsObjectViewsType = Literal["invalid_request_error",]


GetV2ObjectsObjectViewsCode = Literal["not_found",]


class GetV2ObjectsObjectViewsPaginationTypedDict(TypedDict):
    next_cursor: Nullable[str]


class GetV2ObjectsObjectViewsPagination(BaseModel):
    next_cursor: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetV2ObjectsObjectViewsResponseTypedDict(TypedDict):
    r"""Success"""

    data: List[ObjectViewTypedDict]
    pagination: GetV2ObjectsObjectViewsPaginationTypedDict


class GetV2ObjectsObjectViewsResponse(BaseModel):
    r"""Success"""

    data: List[ObjectView]

    pagination: GetV2ObjectsObjectViewsPagination
