"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetV2FilesFileIDDownloadRequestTypedDict(TypedDict):
    file_id: str


class GetV2FilesFileIDDownloadRequest(BaseModel):
    file_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetV2FilesFileIDDownloadResponseTypedDict(TypedDict):
    r"""Redirect"""


class GetV2FilesFileIDDownloadResponse(BaseModel):
    r"""Redirect"""
