"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from attio.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import List, Literal
from typing_extensions import Annotated, NotRequired, TypedDict


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDRequestTypedDict(TypedDict):
    meeting_id: str
    call_recording_id: str


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDRequest(BaseModel):
    meeting_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    call_recording_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDNotFoundType = Literal[
    "invalid_request_error",
]


GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCode = Literal["not_found",]


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDIDTypedDict(TypedDict):
    workspace_id: str
    r"""The ID of the workspace this call recording belongs to."""
    meeting_id: str
    r"""The ID of the meeting associated with this call recording."""
    call_recording_id: str
    r"""The call recording ID of the call recording."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDID(BaseModel):
    workspace_id: str
    r"""The ID of the workspace this call recording belongs to."""

    meeting_id: str
    r"""The ID of the meeting associated with this call recording."""

    call_recording_id: str
    r"""The call recording ID of the call recording."""


GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDStatus = Literal[
    "processing",
    "completed",
    "failed",
]
r"""The status of the call recording. When a call recording is first created, it will have a status of `PROCESSING`. Once the recording is ready, it will transition to `COMPLETED`. If the recording fails for any reason, the status will be `FAILED`."""


GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCreatedByActorType = Literal[
    "api-token",
    "workspace-member",
    "system",
    "app",
]
r"""The type of actor. [Read more information on actor types here](/docs/actors)."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCreatedByActorTypedDict(
    TypedDict
):
    r"""The actor that created this call recording."""

    id: NotRequired[Nullable[str]]
    r"""An ID to identify the actor."""
    type: NotRequired[
        Nullable[GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCreatedByActorType]
    ]
    r"""The type of actor. [Read more information on actor types here](/docs/actors)."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCreatedByActor(BaseModel):
    r"""The actor that created this call recording."""

    id: OptionalNullable[str] = UNSET
    r"""An ID to identify the actor."""

    type: OptionalNullable[
        GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCreatedByActorType
    ] = UNSET
    r"""The type of actor. [Read more information on actor types here](/docs/actors)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type"])
        nullable_fields = set(["id", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDSpeakerTypedDict(TypedDict):
    r"""The speaker of this transcript segment."""

    name: str
    r"""The name of the speaker."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDSpeaker(BaseModel):
    r"""The speaker of this transcript segment."""

    name: str
    r"""The name of the speaker."""


class SegmentTypedDict(TypedDict):
    speech: str
    r"""The spoken text for this segment of the transcript."""
    start_time: float
    r"""The start time of this speech segment in seconds, measured from the start of the recording."""
    end_time: float
    r"""The end time of this speech segment in seconds, measured from the start of the recording."""
    speaker: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDSpeakerTypedDict
    r"""The speaker of this transcript segment."""


class Segment(BaseModel):
    speech: str
    r"""The spoken text for this segment of the transcript."""

    start_time: float
    r"""The start time of this speech segment in seconds, measured from the start of the recording."""

    end_time: float
    r"""The end time of this speech segment in seconds, measured from the start of the recording."""

    speaker: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDSpeaker
    r"""The speaker of this transcript segment."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDTranscriptTypedDict(TypedDict):
    r"""The transcript for this call recording, `null` if no transcript is available."""

    segments: List[SegmentTypedDict]
    r"""The transcript segments with speech, timing, and speaker information."""
    raw_transcript: str
    r"""The raw transcript of the call recording."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDTranscript(BaseModel):
    r"""The transcript for this call recording, `null` if no transcript is available."""

    segments: List[Segment]
    r"""The transcript segments with speech, timing, and speaker information."""

    raw_transcript: str
    r"""The raw transcript of the call recording."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDDataTypedDict(TypedDict):
    id: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDIDTypedDict
    status: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDStatus
    r"""The status of the call recording. When a call recording is first created, it will have a status of `PROCESSING`. Once the recording is ready, it will transition to `COMPLETED`. If the recording fails for any reason, the status will be `FAILED`."""
    web_url: str
    r"""A URL that links directly to the call recording in the Attio web application."""
    created_by_actor: (
        GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCreatedByActorTypedDict
    )
    r"""The actor that created this call recording."""
    created_at: str
    r"""The timestamp of when the call recording was created."""
    video_url: Nullable[str]
    r"""A short-lived URL for downloading the call recording's video. This is only available for call recordings captured by the Attio call recorder: it is always `null` for call recordings created through the API. The URL expires one hour after this response was generated. You can call this endpoint again to get a fresh URL."""
    transcript: Nullable[
        GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDTranscriptTypedDict
    ]
    r"""The transcript for this call recording, `null` if no transcript is available."""


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDData(BaseModel):
    id: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDID

    status: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDStatus
    r"""The status of the call recording. When a call recording is first created, it will have a status of `PROCESSING`. Once the recording is ready, it will transition to `COMPLETED`. If the recording fails for any reason, the status will be `FAILED`."""

    web_url: str
    r"""A URL that links directly to the call recording in the Attio web application."""

    created_by_actor: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDCreatedByActor
    r"""The actor that created this call recording."""

    created_at: str
    r"""The timestamp of when the call recording was created."""

    video_url: Nullable[str]
    r"""A short-lived URL for downloading the call recording's video. This is only available for call recordings captured by the Attio call recorder: it is always `null` for call recordings created through the API. The URL expires one hour after this response was generated. You can call this endpoint again to get a fresh URL."""

    transcript: Nullable[GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDTranscript]
    r"""The transcript for this call recording, `null` if no transcript is available."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDResponseTypedDict(TypedDict):
    r"""Success"""

    data: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDDataTypedDict


class GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDResponse(BaseModel):
    r"""Success"""

    data: GetV2MeetingsMeetingIDCallRecordingsCallRecordingIDData
