"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class GetScimV2GroupsWorkspaceTeamIDRequestTypedDict(TypedDict):
    workspace_team_id: str
    r"""The ID of the SCIM group to retrieve."""


class GetScimV2GroupsWorkspaceTeamIDRequest(BaseModel):
    workspace_team_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the SCIM group to retrieve."""


class GetScimV2GroupsWorkspaceTeamIDMemberTypedDict(TypedDict):
    value: str
    dollar_ref: str


class GetScimV2GroupsWorkspaceTeamIDMember(BaseModel):
    value: str

    dollar_ref: Annotated[str, pydantic.Field(alias="$ref")]


class GetScimV2GroupsWorkspaceTeamIDMetaTypedDict(TypedDict):
    resource_type: str
    created: str
    last_modified: str


class GetScimV2GroupsWorkspaceTeamIDMeta(BaseModel):
    resource_type: Annotated[str, pydantic.Field(alias="resourceType")]

    created: str

    last_modified: Annotated[str, pydantic.Field(alias="lastModified")]


class GetScimV2GroupsWorkspaceTeamIDResponseTypedDict(TypedDict):
    r"""Success"""

    schemas: List[str]
    id: str
    display_name: str
    members: List[GetScimV2GroupsWorkspaceTeamIDMemberTypedDict]
    meta: GetScimV2GroupsWorkspaceTeamIDMetaTypedDict


class GetScimV2GroupsWorkspaceTeamIDResponse(BaseModel):
    r"""Success"""

    schemas: List[str]

    id: str

    display_name: Annotated[str, pydantic.Field(alias="displayName")]

    members: List[GetScimV2GroupsWorkspaceTeamIDMember]

    meta: GetScimV2GroupsWorkspaceTeamIDMeta


try:
    GetScimV2GroupsWorkspaceTeamIDMember.model_rebuild()
except NameError:
    pass
try:
    GetScimV2GroupsWorkspaceTeamIDMeta.model_rebuild()
except NameError:
    pass
try:
    GetScimV2GroupsWorkspaceTeamIDResponse.model_rebuild()
except NameError:
    pass
