"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class GetScimV2UsersUserIDRequestTypedDict(TypedDict):
    user_id: str
    r"""The ID of the SCIM user to retrieve."""


class GetScimV2UsersUserIDRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the SCIM user to retrieve."""


class GetScimV2UsersUserIDNameTypedDict(TypedDict):
    family_name: str
    given_name: str


class GetScimV2UsersUserIDName(BaseModel):
    family_name: Annotated[str, pydantic.Field(alias="familyName")]

    given_name: Annotated[str, pydantic.Field(alias="givenName")]


class GetScimV2UsersUserIDEmailTypedDict(TypedDict):
    value: str
    primary: bool


class GetScimV2UsersUserIDEmail(BaseModel):
    value: str

    primary: bool


class GetScimV2UsersUserIDRoleTypedDict(TypedDict):
    value: str
    primary: bool


class GetScimV2UsersUserIDRole(BaseModel):
    value: str

    primary: bool


class GetScimV2UsersUserIDMetaTypedDict(TypedDict):
    resource_type: str
    created: str
    last_modified: str


class GetScimV2UsersUserIDMeta(BaseModel):
    resource_type: Annotated[str, pydantic.Field(alias="resourceType")]

    created: str

    last_modified: Annotated[str, pydantic.Field(alias="lastModified")]


class GetScimV2UsersUserIDResponseTypedDict(TypedDict):
    r"""Success"""

    schemas: List[str]
    id: str
    user_name: str
    name: GetScimV2UsersUserIDNameTypedDict
    emails: List[GetScimV2UsersUserIDEmailTypedDict]
    active: bool
    roles: List[GetScimV2UsersUserIDRoleTypedDict]
    meta: GetScimV2UsersUserIDMetaTypedDict


class GetScimV2UsersUserIDResponse(BaseModel):
    r"""Success"""

    schemas: List[str]

    id: str

    user_name: Annotated[str, pydantic.Field(alias="userName")]

    name: GetScimV2UsersUserIDName

    emails: List[GetScimV2UsersUserIDEmail]

    active: bool

    roles: List[GetScimV2UsersUserIDRole]

    meta: GetScimV2UsersUserIDMeta


try:
    GetScimV2UsersUserIDName.model_rebuild()
except NameError:
    pass
try:
    GetScimV2UsersUserIDMeta.model_rebuild()
except NameError:
    pass
try:
    GetScimV2UsersUserIDResponse.model_rebuild()
except NameError:
    pass
