"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from typing_extensions import TypedDict


class ListViewIDTypedDict(TypedDict):
    workspace_id: str
    r"""A UUID identifying the workspace this view belongs to."""
    list_id: str
    r"""A UUID identifying the list this view belongs to."""
    view_id: str
    r"""A UUID identifying this view. Use this value as `filter_view_id` when listing entries."""


class ListViewID(BaseModel):
    workspace_id: str
    r"""A UUID identifying the workspace this view belongs to."""

    list_id: str
    r"""A UUID identifying the list this view belongs to."""

    view_id: str
    r"""A UUID identifying this view. Use this value as `filter_view_id` when listing entries."""


class ListViewTypedDict(TypedDict):
    id: ListViewIDTypedDict
    title: str
    r"""The title of the view shown in the Attio app."""
    created_at: str
    r"""When the view was created."""


class ListView(BaseModel):
    id: ListViewID

    title: str
    r"""The title of the view shown in the Attio app."""

    created_at: str
    r"""When the view was created."""
