"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from typing_extensions import TypedDict


class ObjectViewIDTypedDict(TypedDict):
    workspace_id: str
    r"""A UUID identifying the workspace this view belongs to."""
    object_id: str
    r"""A UUID identifying the object this view belongs to."""
    view_id: str
    r"""A UUID identifying this view. Use this value as `filter_view_id` when listing records."""


class ObjectViewID(BaseModel):
    workspace_id: str
    r"""A UUID identifying the workspace this view belongs to."""

    object_id: str
    r"""A UUID identifying the object this view belongs to."""

    view_id: str
    r"""A UUID identifying this view. Use this value as `filter_view_id` when listing records."""


class ObjectViewTypedDict(TypedDict):
    id: ObjectViewIDTypedDict
    title: str
    r"""The title of the view shown in the Attio app."""
    created_at: str
    r"""When the view was created."""


class ObjectView(BaseModel):
    id: ObjectViewID

    title: str
    r"""The title of the view shown in the Attio app."""

    created_at: str
    r"""When the view was created."""
