"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel, Nullable, UNSET_SENTINEL
from attio.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class PatchScimV2UsersUserIDRequestTypedDict(TypedDict):
    user_id: str
    r"""The ID of the SCIM user to update."""


class PatchScimV2UsersUserIDRequest(BaseModel):
    user_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the SCIM user to update."""


class PatchScimV2UsersUserIDResponseBody2TypedDict(TypedDict):
    r"""No Content"""


class PatchScimV2UsersUserIDResponseBody2(BaseModel):
    r"""No Content"""


class PatchScimV2UsersUserIDNameTypedDict(TypedDict):
    given_name: str
    family_name: str


class PatchScimV2UsersUserIDName(BaseModel):
    given_name: Annotated[str, pydantic.Field(alias="givenName")]

    family_name: Annotated[str, pydantic.Field(alias="familyName")]


class PatchScimV2UsersUserIDEmailTypedDict(TypedDict):
    value: str
    primary: bool
    type: NotRequired[str]


class PatchScimV2UsersUserIDEmail(BaseModel):
    value: str

    primary: bool

    type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PatchScimV2UsersUserIDRoleTypedDict(TypedDict):
    value: str
    primary: bool


class PatchScimV2UsersUserIDRole(BaseModel):
    value: str

    primary: bool


class PatchScimV2UsersUserIDMetaTypedDict(TypedDict):
    resource_type: str
    created: str
    last_modified: str


class PatchScimV2UsersUserIDMeta(BaseModel):
    resource_type: Annotated[str, pydantic.Field(alias="resourceType")]

    created: str

    last_modified: Annotated[str, pydantic.Field(alias="lastModified")]


class PatchScimV2UsersUserIDResponseBody1TypedDict(TypedDict):
    r"""Success"""

    schemas: List[str]
    id: str
    user_name: str
    name: PatchScimV2UsersUserIDNameTypedDict
    emails: List[PatchScimV2UsersUserIDEmailTypedDict]
    roles: List[PatchScimV2UsersUserIDRoleTypedDict]
    profile_url: Nullable[str]
    active: bool
    meta: PatchScimV2UsersUserIDMetaTypedDict


class PatchScimV2UsersUserIDResponseBody1(BaseModel):
    r"""Success"""

    schemas: List[str]

    id: str

    user_name: Annotated[str, pydantic.Field(alias="userName")]

    name: PatchScimV2UsersUserIDName

    emails: List[PatchScimV2UsersUserIDEmail]

    roles: List[PatchScimV2UsersUserIDRole]

    profile_url: Annotated[Nullable[str], pydantic.Field(alias="profileUrl")]

    active: bool

    meta: PatchScimV2UsersUserIDMeta

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


PatchScimV2UsersUserIDResponseTypedDict = TypeAliasType(
    "PatchScimV2UsersUserIDResponseTypedDict",
    Union[
        PatchScimV2UsersUserIDResponseBody2TypedDict,
        PatchScimV2UsersUserIDResponseBody1TypedDict,
    ],
)


PatchScimV2UsersUserIDResponse = TypeAliasType(
    "PatchScimV2UsersUserIDResponse",
    Union[PatchScimV2UsersUserIDResponseBody2, PatchScimV2UsersUserIDResponseBody1],
)


try:
    PatchScimV2UsersUserIDName.model_rebuild()
except NameError:
    pass
try:
    PatchScimV2UsersUserIDMeta.model_rebuild()
except NameError:
    pass
try:
    PatchScimV2UsersUserIDResponseBody1.model_rebuild()
except NameError:
    pass
