"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class PatchScimV2GroupsWorkspaceTeamIDRequestTypedDict(TypedDict):
    workspace_team_id: str
    r"""The ID of the SCIM group to update."""


class PatchScimV2GroupsWorkspaceTeamIDRequest(BaseModel):
    workspace_team_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the SCIM group to update."""


class PatchScimV2GroupsWorkspaceTeamIDMemberTypedDict(TypedDict):
    value: str
    dollar_ref: str


class PatchScimV2GroupsWorkspaceTeamIDMember(BaseModel):
    value: str

    dollar_ref: Annotated[str, pydantic.Field(alias="$ref")]


class PatchScimV2GroupsWorkspaceTeamIDMetaTypedDict(TypedDict):
    resource_type: str
    created: str
    last_modified: str


class PatchScimV2GroupsWorkspaceTeamIDMeta(BaseModel):
    resource_type: Annotated[str, pydantic.Field(alias="resourceType")]

    created: str

    last_modified: Annotated[str, pydantic.Field(alias="lastModified")]


class PatchScimV2GroupsWorkspaceTeamIDResponseTypedDict(TypedDict):
    r"""Success"""

    schemas: List[str]
    id: str
    display_name: str
    members: List[PatchScimV2GroupsWorkspaceTeamIDMemberTypedDict]
    meta: PatchScimV2GroupsWorkspaceTeamIDMetaTypedDict


class PatchScimV2GroupsWorkspaceTeamIDResponse(BaseModel):
    r"""Success"""

    schemas: List[str]

    id: str

    display_name: Annotated[str, pydantic.Field(alias="displayName")]

    members: List[PatchScimV2GroupsWorkspaceTeamIDMember]

    meta: PatchScimV2GroupsWorkspaceTeamIDMeta


try:
    PatchScimV2GroupsWorkspaceTeamIDMember.model_rebuild()
except NameError:
    pass
try:
    PatchScimV2GroupsWorkspaceTeamIDMeta.model_rebuild()
except NameError:
    pass
try:
    PatchScimV2GroupsWorkspaceTeamIDResponse.model_rebuild()
except NameError:
    pass
