"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from typing import Any, Dict, List, Literal
from typing_extensions import TypedDict


class PostV2SQLRequestTypedDict(TypedDict):
    sql: str
    r"""The SQL query to be executed."""


class PostV2SQLRequest(BaseModel):
    sql: str
    r"""The SQL query to be executed."""


PostV2SQLType = Literal["invalid_request_error",]


PostV2SQLCode = Literal["filter_error",]


class PostV2SQLDataTypedDict(TypedDict):
    rows: List[Dict[str, Any]]


class PostV2SQLData(BaseModel):
    rows: List[Dict[str, Any]]


class PostV2SQLResponseTypedDict(TypedDict):
    r"""Success"""

    data: PostV2SQLDataTypedDict


class PostV2SQLResponse(BaseModel):
    r"""Success"""

    data: PostV2SQLData
