"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class PostScimV2GroupsMemberTypedDict(TypedDict):
    value: str
    dollar_ref: str


class PostScimV2GroupsMember(BaseModel):
    value: str

    dollar_ref: Annotated[str, pydantic.Field(alias="$ref")]


class PostScimV2GroupsMetaTypedDict(TypedDict):
    resource_type: str
    created: str
    last_modified: str


class PostScimV2GroupsMeta(BaseModel):
    resource_type: Annotated[str, pydantic.Field(alias="resourceType")]

    created: str

    last_modified: Annotated[str, pydantic.Field(alias="lastModified")]


class PostScimV2GroupsResponseTypedDict(TypedDict):
    r"""Created"""

    schemas: List[str]
    id: str
    display_name: str
    members: List[PostScimV2GroupsMemberTypedDict]
    meta: PostScimV2GroupsMetaTypedDict


class PostScimV2GroupsResponse(BaseModel):
    r"""Created"""

    schemas: List[str]

    id: str

    display_name: Annotated[str, pydantic.Field(alias="displayName")]

    members: List[PostScimV2GroupsMember]

    meta: PostScimV2GroupsMeta


try:
    PostScimV2GroupsMember.model_rebuild()
except NameError:
    pass
try:
    PostScimV2GroupsMeta.model_rebuild()
except NameError:
    pass
try:
    PostScimV2GroupsResponse.model_rebuild()
except NameError:
    pass
