"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .file import File, FileTypedDict
from attio.types import BaseModel, UNSET_SENTINEL
from attio.utils import FieldMetadata, MultipartFormMetadata
import io
import pydantic
from pydantic import model_serializer
from typing import IO, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class PostV2FilesUploadFileTypedDict(TypedDict):
    file_name: str
    content: Union[bytes, IO[bytes], io.IOBase]
    content_type: NotRequired[str]


class PostV2FilesUploadFile(BaseModel):
    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content: Annotated[
        Union[bytes, IO[bytes], io.IOBase],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["contentType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostV2FilesUploadRequestTypedDict(TypedDict):
    file: PostV2FilesUploadFileTypedDict
    r"""The file to upload."""
    object: str
    r"""The object slug or ID."""
    record_id: str
    r"""The ID of the record to upload the file to."""
    parent_folder_id: NotRequired[str]
    r"""Optional parent folder ID. Omit to upload to the root folder."""


class PostV2FilesUploadRequest(BaseModel):
    file: Annotated[
        PostV2FilesUploadFile, FieldMetadata(multipart=MultipartFormMetadata(file=True))
    ]
    r"""The file to upload."""

    object: Annotated[str, FieldMetadata(multipart=True)]
    r"""The object slug or ID."""

    record_id: Annotated[str, FieldMetadata(multipart=True)]
    r"""The ID of the record to upload the file to."""

    parent_folder_id: Annotated[Optional[str], FieldMetadata(multipart=True)] = None
    r"""Optional parent folder ID. Omit to upload to the root folder."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["parent_folder_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


PostV2FilesUploadType = Literal["auth_error",]


PostV2FilesUploadCodeQuotaExceeded = Literal["quota_exceeded",]


PostV2FilesUploadCodeBillingError = Literal["billing_error",]


PostV2FilesUploadCodeUnionTypedDict = TypeAliasType(
    "PostV2FilesUploadCodeUnionTypedDict",
    Union[PostV2FilesUploadCodeBillingError, PostV2FilesUploadCodeQuotaExceeded],
)


PostV2FilesUploadCodeUnion = TypeAliasType(
    "PostV2FilesUploadCodeUnion",
    Union[PostV2FilesUploadCodeBillingError, PostV2FilesUploadCodeQuotaExceeded],
)


class PostV2FilesUploadResponseTypedDict(TypedDict):
    r"""Created"""

    data: FileTypedDict


class PostV2FilesUploadResponse(BaseModel):
    r"""Created"""

    data: File
