"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel
from attio.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class PutScimV2GroupsWorkspaceTeamIDRequestTypedDict(TypedDict):
    workspace_team_id: str
    r"""The ID of the SCIM group to replace."""


class PutScimV2GroupsWorkspaceTeamIDRequest(BaseModel):
    workspace_team_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the SCIM group to replace."""


class PutScimV2GroupsWorkspaceTeamIDMemberTypedDict(TypedDict):
    value: str
    dollar_ref: str


class PutScimV2GroupsWorkspaceTeamIDMember(BaseModel):
    value: str

    dollar_ref: Annotated[str, pydantic.Field(alias="$ref")]


class PutScimV2GroupsWorkspaceTeamIDMetaTypedDict(TypedDict):
    resource_type: str
    created: str
    last_modified: str


class PutScimV2GroupsWorkspaceTeamIDMeta(BaseModel):
    resource_type: Annotated[str, pydantic.Field(alias="resourceType")]

    created: str

    last_modified: Annotated[str, pydantic.Field(alias="lastModified")]


class PutScimV2GroupsWorkspaceTeamIDResponseTypedDict(TypedDict):
    r"""Success"""

    schemas: List[str]
    id: str
    display_name: str
    members: List[PutScimV2GroupsWorkspaceTeamIDMemberTypedDict]
    meta: PutScimV2GroupsWorkspaceTeamIDMetaTypedDict


class PutScimV2GroupsWorkspaceTeamIDResponse(BaseModel):
    r"""Success"""

    schemas: List[str]

    id: str

    display_name: Annotated[str, pydantic.Field(alias="displayName")]

    members: List[PutScimV2GroupsWorkspaceTeamIDMember]

    meta: PutScimV2GroupsWorkspaceTeamIDMeta


try:
    PutScimV2GroupsWorkspaceTeamIDMember.model_rebuild()
except NameError:
    pass
try:
    PutScimV2GroupsWorkspaceTeamIDMeta.model_rebuild()
except NameError:
    pass
try:
    PutScimV2GroupsWorkspaceTeamIDResponse.model_rebuild()
except NameError:
    pass
