"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class StatusIDTypedDict(TypedDict):
    workspace_id: str
    r"""The ID of the workspace"""
    object_id: str
    r"""The ID of the object"""
    attribute_id: str
    r"""The ID of the attribute"""
    status_id: str
    r"""The ID of the status"""


class StatusID(BaseModel):
    workspace_id: str
    r"""The ID of the workspace"""

    object_id: str
    r"""The ID of the object"""

    attribute_id: str
    r"""The ID of the attribute"""

    status_id: str
    r"""The ID of the status"""


class StatusTypedDict(TypedDict):
    id: StatusIDTypedDict
    title: str
    r"""The title of the status"""
    is_archived: bool
    r"""Whether or not to archive the status. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving."""
    celebration_enabled: bool
    r"""Whether arriving at this status triggers a celebration effect in the UI"""
    target_time_in_status: Nullable[str]
    r"""Target time for a record to spend in given status expressed as a ISO-8601 duration string"""


class Status(BaseModel):
    id: StatusID

    title: str
    r"""The title of the status"""

    is_archived: bool
    r"""Whether or not to archive the status. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving."""

    celebration_enabled: bool
    r"""Whether arriving at this status triggers a celebration effect in the UI"""

    target_time_in_status: Nullable[str]
    r"""Target time for a record to spend in given status expressed as a ISO-8601 duration string"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
