"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from attio.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal
from typing_extensions import TypedDict


class WorkspaceMemberIDTypedDict(TypedDict):
    workspace_id: str
    r"""The ID of the workspace the workspace member belongs to."""
    workspace_member_id: str
    r"""The ID of the workspace member."""


class WorkspaceMemberID(BaseModel):
    workspace_id: str
    r"""The ID of the workspace the workspace member belongs to."""

    workspace_member_id: str
    r"""The ID of the workspace member."""


AccessLevel = Literal[
    "admin",
    "member",
    "suspended",
]
r"""Whether the workspace member is suspended or not and what level of privileges they have inside the workspace. We do not delete workspace members so that you can successfully attribute past actions to suspended workspace members."""


class WorkspaceMemberTypedDict(TypedDict):
    id: WorkspaceMemberIDTypedDict
    first_name: str
    r"""The first name of the user."""
    last_name: str
    r"""The last name of the user."""
    avatar_url: Nullable[str]
    r"""A URL to the user's avatar image."""
    email_address: str
    r"""The user's email address."""
    created_at: str
    r"""When the workspace member was created."""
    access_level: AccessLevel
    r"""Whether the workspace member is suspended or not and what level of privileges they have inside the workspace. We do not delete workspace members so that you can successfully attribute past actions to suspended workspace members."""


class WorkspaceMember(BaseModel):
    id: WorkspaceMemberID

    first_name: str
    r"""The first name of the user."""

    last_name: str
    r"""The last name of the user."""

    avatar_url: Nullable[str]
    r"""A URL to the user's avatar image."""

    email_address: str
    r"""The user's email address."""

    created_at: str
    r"""When the workspace member was created."""

    access_level: AccessLevel
    r"""Whether the workspace member is suspended or not and what level of privileges they have inside the workspace. We do not delete workspace members so that you can successfully attribute past actions to suspended workspace members."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
