name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - uses: dagger/dagger-for-github@v8.4.1

      - name: Generate SDK
        run: uv run python ci/pipeline.py generate
        env:
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAGGER_PROGRESS: plain
          OTEL_SDK_DISABLED: "true"
      - uses: peter-evans/create-pull-request@v8
        with:
          branch: gha/attio-sdk-generation
          base: main
          commit-message: "feat(sdk): regenerate attio SDK"
          labels: automated, sdk
          delete-branch: true
